# Generated by Django 4.2.6 on 2023-10-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
