# Generated by Django 4.2.6 on 2023-11-24 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('titular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'db_table': 'balance',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='HistorialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('Depósito', 'Depósito'), ('Retiro', 'Retiro')], max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.balance')),
            ],
            options={
                'verbose_name': 'Historial de Balance',
                'verbose_name_plural': 'Historiales de Balance',
                'db_table': 'historial_balance',
                'ordering': ['-fecha'],
            },
        ),
    ]
