# Generated by Django 4.2.6 on 2023-11-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['pk'], 'verbose_name': 'Balance', 'verbose_name_plural': 'Balances'},
        ),
        migrations.AlterModelTable(
            name='balance',
            table='balance',
        ),
    ]
