# Generated by Django 4.2.6 on 2023-11-23 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_balance_options_alter_balance_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='HistorialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('Depósito', 'Depósito'), ('Retiro', 'Retiro')], max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.balance')),
            ],
            options={
                'verbose_name': 'Historial de Balance',
                'verbose_name_plural': 'Historiales de Balance',
                'db_table': 'historial_balance',
                'ordering': ['-fecha'],
            },
        ),
    ]
