# Generated by Django 4.2.6 on 2023-11-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_categoria_genero_producto_categoria_producto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
        migrations.AddField(
            model_name='producto',
            name='generos',
            field=models.ManyToManyField(to='producto.genero'),
        ),
    ]
